#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! npx --no -- commitlint --edit "${1}"; then
    # Copy the non-comment lines
    grep -v '^#' "${1}" > "${1}.aborted"

    echo "If using the CLI, your message will be recovered if you commit again without a message."
    exit 1
fi
